### ISSUE TITLE
missing file in kuka_push

### ISSUE THREAD

**Issue by ey39** [TomasMerva/ROS_KUKA_env#2]
hello Tomas!
Is your "kuka_push" folder missing some of the files included in "kuka_push/include.h"

#include <kuka_push/rl_env.h>
#include <kuka_push/object_reset.h>
#include <kuka_push/object_pose_vel.h>

**Comment by TomasMerva** [comment]
Hi,

Because I lacked knowledge, I created custom messages and service types within the `kuka_push` package. That is the reason, why I believe you have trouble compiling the package. Either you create a new package dedicated to custom messages, or you need to comment the executable in CMakeLists for `kuka_push` -> compile messages -> uncomment the executable in CMakeLists.

https://github.com/TomasMerva/ROS_KUKA_env/tree/master/kuka_push/srv
https://github.com/TomasMerva/ROS_KUKA_env/tree/master/kuka_push/msg

**Comment by ey39** [comment]
> Hi,
> 
> Because I lacked knowledge, I created custom messages and service types within the `kuka_push` package. That is the reason, why I believe you have trouble compiling the package. Either you create a new package dedicated to custom messages, or you need to comment the executable in CMakeLists for `kuka_push` -> compile messages -> uncomment the executable in CMakeLists.
> 
> https://github.com/TomasMerva/ROS_KUKA_env/tree/master/kuka_push/srv https://github.com/TomasMerva/ROS_KUKA_env/tree/master/kuka_push/msg

Thank you for the response! I really hadn't thought about that.
I have compiled the project successfully after commenting the executable in CMakeLists for `kuka_push` and uncommenting it.

Additionally,I ran it under ros-noetic, and since noetic is not compatible with gazebo9, there are still a few changes that need to be made:

firstly, in the file "kuka_push/plugin/goalgazebo.h", I need to comment out these two lines, probably because of a version update. gazebo11 already comes with the ignitionmath library
// #include <ignition/math4/ignition/math/Vector3.hh>
// #include <ignition/math4/ignition/math/Pose3.hh>
the same as "kuka_push/plugin/pushobject.h"

secondly,  in CMakeLists for `kuka_push`, gazebo version should be changed
from # find_package(gazebo 9 REQUIRED) -> find_package(gazebo REQUIRED)

**Comment by TomasMerva** [comment]
Honestly, I do not have time right now to refactor this repo, but if you create a pull request I will check it :)

However, I would recommend using a simulator other than Gazebo, especially for reinforcement learning, e.g. Mujoco or Isaac Gym.

**Comment by ey39** [comment]
> Honestly, I do not have time right now to refactor this repo, but if you create a pull request I will check it :)
> 
> However, I would recommend using a simulator other than Gazebo, especially for reinforcement learning, e.g. Mujoco or Isaac Gym.

I will arrange some time in the near future to deal with this issue. At the same time, I would also like to thank you for your advice on the simulator selection. I did realize that Gazebo might not be the best choice for a reinforcement learning experiment.

I'll explore MuJoCo and Isaac Gym further and you're more than welcome to review them again.

Thanks again for your feedback and suggestions.

Best regards,
